### ISSUE TITLE
Replace wrong name for nvm

### ISSUE THREAD

**Issue by Bernstein7z** [pawelgrzybek/pawelgrzybek.com#151]
I assume the second `npm` should be `nvm`.

https://github.com/pawelgrzybek/pawelgrzybek.com/blob/2fa75393f0129609a2922a1ac30c54821ab004fb/content/posts/2023-12-01-i-replaced-npm-yarn-and-nvm-with-pnpm/index.md?plain=1#L8

**Comment by pawelgrzybek** [comment]
You are an absolute hero and a good example of how to contribute to open source! Not many people took the effort to correct some spelling mistakes on the blog via GitHub issues. I really appreciate your help.
