### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by niutech** [pawelgrzybek/pawelgrzybek.com#184]
There is a typo, it should be `<section>`:

https://github.com/pawelgrzybek/pawelgrzybek.com/blob/6f4ddcbad0b8edff69b172f61adf35438ee6c538/themes/pawelgrzybek/layouts/shortcodes/baseline.html#L13

**Comment by pawelgrzybek** [comment]
Dziękuję bardzo :) Dlatego się niegdzie wywalał layout. Plusy i minusy korzystania z modern/olschoolowych IDEs :)

Dziękuję raz jeszcze i pozdrawiam!
