### ISSUE TITLE
Dark theme - comments section

### ISSUE THREAD

**Issue by fhavrlent** [pawelgrzybek/pawelgrzybek.com#42]
Font color of comments section is a "bit" off for dark theme 🦀.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/16169571/82825601-d4805d80-9eab-11ea-9d2c-30bc164d6b9f.png">

**Comment by pawelgrzybek** [comment]
This is fantastic spot. I need to adjust Discuss theme too.

Thanks @fhavrlent and have a lovely day!

**Comment by pawelgrzybek** [comment]
It is fixed now. Thanks again!
